# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 07:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hobbies', '0002_auto_20170701_0723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub_Categories_Sub_Categories1_Mapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hobbies.Sub_Categories')),
                ('sub_category1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hobbies.Sub_Categories1')),
            ],
        ),
    ]
