# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 07:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Hobbies', '0003_sub_categories_sub_categories1_mapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('video', models.CharField(max_length=300)),
                ('image', models.CharField(max_length=300)),
                ('sub_category1_map_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hobbies.Sub_Categories_Sub_Categories1_Mapping')),
            ],
        ),
        migrations.RenameModel(
            old_name='Category_Sub_Category_Mapping',
            new_name='Categories_Sub_Categories_Mapping',
        ),
        migrations.AddField(
            model_name='sub_categories1',
            name='sub_category1',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sub_categories1',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hobbies.Sub_Categories'),
        ),
    ]
