# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 08:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hobbies', '0004_auto_20170701_0743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details_Utilities_Mapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hobbies.Details')),
            ],
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=50)),
                ('suggesions', models.CharField(max_length=50)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hobbies.Categories')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(max_length=50)),
                ('post_adv', models.BooleanField()),
                ('img', models.CharField(max_length=300)),
                ('video', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ScoreBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hobbies.Categories')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hobbies.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Utilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utility', models.CharField(max_length=50)),
                ('links', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='details_utilities_mapping',
            name='utility_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hobbies.Utilities'),
        ),
    ]
